### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#100]
Remove unnecessary files that didn't goes with Title.

**Comment by ParthS007** [comment]
@STEdirisuriya please give details about the files that you want to remove

**Comment by nzec** [comment]
This issue is obscure and @STEdirisuriya has not given any more details.
I think this should be closed. @fossasia/fossasia-gci

**Comment by ba11b0y** [comment]
@STEdirisuriya Please elaborate on this issue.

**Comment by supunTE** [comment]
I said about the details that don't going with FOSSASIA. You have to delete them. And delete unuseful things for students.

**Comment by sudheesh001** [comment]
@STEdirisuriya We are still not clear on what you're asking for. What are the unuseful things for students here that needs to be removed? Can you point to some of them that should be removed. I am in the meanwhile closing this issue and happy to reopen it if it can be better phrased with a goal in mind.
