### ISSUE TITLE
Redirect Index Page Broken

### ISSUE THREAD

**Issue by Abuissink** [fossasia/gci17.fossasia.org#11]
Hi all,
@royalharsh's commit 798195d, "Fixed Website" actually broke the index.html file. The only point of that file is to redirect users to the en/index.html. This is needed as you cannot change the default page in gh-pages. Where the confusion came from is that when running the site through `file://`, a localhost (eg Brackets' Live Preview) or a domain/subdomain, like if this ever makes it to `whatcanidofor.fossasia.org` the folder `en` is a first level folder, eg `domain.com/en` but because of the way GitHub Pages works, the website is `...github.io/whatcanidoforfossasia.org/en`. Royalharsh's commit fixes the website when it isn't in gh-pages, but now index.html tries to load the index.html of a different repo, `en`, which doesn't exist. The `whatcanidoforfossasia.org/en/index.html` is necessary on GitHub Pages to make sure it loads correctly.

**Comment by mariobehling** [comment]
@Abuissink Thanks for your input. I think the different approaches are also resulting from using automated tools (e.g. asknot-ng) or building a site manually. At the moment the main goal is to have an English decision tree, that makes sense as well. We can also iterate step by step. You made a very nice first version. Thank you! Now we need to come up with a good plan for this site. I simplified the site by moving the /en content into the main folder as well. I am closing this issue therefore. Cheers!

**Comment by mariobehling** [comment]
@Abuissink @royalharsh I have added a task to get input of students, so we come up with a better Q&A tree: https://codein.withgoogle.com/tasks/6440849055416320/?sp-organization=4625502878826496
