### ISSUE TITLE
Add documentation on how to add a student

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#111]
We got a nice simple set of instructions on how to add a mentor in readme but not the student.
Can we have that as well?

**Comment by nzec** [comment]
@abishekvashok On it! I will also add instructions for Student Projects in the Readme.

**Comment by AKostiv8** [comment]
I have already done it

**Comment by nzec** [comment]
@abishekvashok Added Student and Projects documentation and some notes in #114 

(I know @AKostiv8 solved it before me but I also added other stuff.)

See it at : https://github.com/duttaditya18/gci17.fossasia.org/blob/gh-pages/README.md

**Comment by nzec** [comment]
My PR just got accepted. This issue can be closed now.
