### ISSUE TITLE
Animations to the site ?

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/gci17.fossasia.org#125]
### Expected results
How about adding animations to our site ?

### Actual results
It's just there. :/ No animations.

### Steps to reproduce the issue
Just use a open source library and add animations

## Would you like to work on this
Yes !

**Comment by anshumanv** [comment]
Please go ahead @YashKumarVerma :smile: 
Cool Idea!

**Comment by YashKumarVerma** [comment]
for now, i'm adding fadeIn animations to the headings using animate.css . as the content increases on the site, others headings would be covered too.
[https://daneden.github.io/animate.css/](https://daneden.github.io/animate.css/)

**Comment by nzec** [comment]
@YashKumarVerma Maybe add a hover animation on the images? I think that would look good. I do not know for sure though.
Good luck.

**Comment by YashKumarVerma** [comment]
working on it @duttaditya18

**Comment by YashKumarVerma** [comment]
will be adding in near future
