### ISSUE TITLE
Problem in scripts and merging.

### ISSUE THREAD

**Issue by nzec** [fossasia/gci17.fossasia.org#136]
### Expected results
* Scripts properly working. (Smooth Scroll, Map)

### Actual results
* Someone did not merge the right way which resulted in these : https://imgur.com/a/JFg1q
* Mentors and Contributors are rendering without Jekyll.
* Jekyll inside JS is causing problems.

### Steps to reproduce the issue
Fix whatever is wrong.

## Would you like to work on this
I do not understand what is going on. Someone. Please look into this.

**Comment by nzec** [comment]
So I looked into this and found out that the problem is being caused due to 477f1b1cba8bbd44f92c3ce3ab7b03053acb8203
In my belief, @STEdirisuriya compiled the Jekyll and merged it. I would request @fossasia/fossasia-gci to look into this.

**Comment by ryushar** [comment]
I hope the pull request that Ill make soon will fix most of it.
https://2coolife.github.io/gci17.fossasia.org/
fixed merge conflicts and using jekyll templates again.
Gonna fix some more stuff and then make a pull request.

**Comment by nzec** [comment]
@2coolife That is so awesome of you.

**Comment by ryushar** [comment]
:smile: I think this would take care of it.

**Comment by abishekvashok** [comment]
@duttaditya18 that was becasue
```
---
---
```

were missing on top of index.html, that two lines tell jekyll that it is used in the file :)

**Comment by nzec** [comment]
@abishekvashok Still doesn't look like it is fixed.

**Comment by abishekvashok** [comment]
who's working on it?

**Comment by abishekvashok** [comment]
Taking it up as it's a priority issue.

**Comment by abishekvashok** [comment]
@fossasia/fossasia-gci can we revert #118 as it built jekyll on his local machine and removed keyll dynamic code with static one?

**Comment by anshumanv** [comment]
@abishekvashok that seems to be the only solution to this, but it was merged long back and a lot of changes have been done since then, we will lose a lot of data, can you think of another workaround else this is the only path we can take.

**Comment by nzec** [comment]
@anshumanv @abishekvashok This issue was fixed by #138. Closing this right now.
