### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by yasoob** [fossasia/gci17.fossasia.org#14]
Currently when it reached the `code` slide, everything disappears. I am not pro-efficient in JS otherwise I would have loved to solve this issue. :+1:

**Comment by jig08** [comment]
@yasoob +1
Link: http://whatcanidofor.fossasia.org/#code

**Comment by jigyasa-grover** [comment]
@yasoob +1

![screenshot from 2015-12-31 11 22 35](https://cloud.githubusercontent.com/assets/9291400/12061615/dcf7c488-afb0-11e5-8211-f1b74a16f6e8.png)

**Comment by jigyasa-grover** [comment]
But if we directly jump to [whatcanidofor.fossasia.org/#code](http://whatcanidofor.fossasia.org/#code) it seems to work :confused:

**Comment by sudheesh001** [comment]
Even if `#code` works directly in the given link, the next link `http://whatcanidofor.fossasia.org/#making-things-stable` goes blank but refreshing that works, this is interesting.

**Comment by mariobehling** [comment]
Actually, we have so many real projects. This project should be deprecated.
