### ISSUE TITLE
Unnecessary HEAD tag

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/gci17.fossasia.org#148]
### Expected results
Head tag should be removed
### Actual results
![bug](https://user-images.githubusercontent.com/15213246/33664603-3dee5618-daba-11e7-88d8-c5b4a0fa41dc.png)
### Steps to reproduce the issue
https://gci17.fossasia.org/

**Comment by ba11b0y** [comment]
@meets2tarun This was introduced because of a wrong merge by me. This already has a PR, please wait while it is fixed

**Comment by the-codingninja** [comment]
It is already fixed
Cheers!!
