### ISSUE TITLE
Readme Typo Error

### ISSUE THREAD

**Issue by niranjannitesh** [fossasia/gci17.fossasia.org#151]
## Expected results
**Adding a Student**
To add a student open the file `students.yml `in `_data` folder and please maintain the following format EXACTLY (replacing values where indicated):

**Adding a Student Project**
To add a student project open the file `student_projects.yml `in `_data` folder and please maintain the following format EXACTLY (replacing values where indicated):

### Actual results
**Adding a Student**
To add a mentor open the file `students.yml` in `_data` folder and please maintain the following format EXACTLY (replacing values where indicated):

**Adding a Student Project**
To add a mentor open the file `student_projects.yml `in `_data `folder and please maintain the following format EXACTLY (replacing values where indicated):

## Would you like to work on this

**Comment by abishekvashok** [comment]
@niteshkumarniranjan pls go  on

**Comment by 0x48piraj** [comment]
I can do it. Will give it a try!

**Comment by awesometushar000** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/164

**Comment by the-codingninja** [comment]
This issue was fixed hence closing it!!
Cheers :sparkles:
