### ISSUE TITLE
Resize images which are out of dimension.

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#166]
### Expected results
Images should be in correct dimensions, 240x240 px.

### Actual results
11 image(s) have greater dimensions then specified.

The images are exactly as follows (reported by img_checker integrated on #165 )

>The image ./img/blog/1.jpg is larger than 240px x 240px [w x h]
The image ./img/blog/3.jpg is larger than 240px x 240px [w x h]
The image ./img/blog/2.jpg is larger than 240px x 240px [w x h]
The image ./img/mentors/ansh.jpg is larger than 240px x 240px [w x h]
The image ./img/mentors/niccokunzmann.png is larger than 240px x 240px [w x h]
The image ./img/students/aryankedare.jpg is larger than 240px x 240px [w x h]
The image ./img/students/chahat.png is larger than 240px x 240px [w x h]
The image ./img/students/cagriari.jpg is larger than 240px x 240px [w x h]
The image ./img/students/m1guelpf.png is larger than 240px x 240px [w x h]
The image ./img/students/kostiv.jpg is larger than 240px x 240px [w x h]
The image ./img/students/kuba-michalski.jpg is larger than 240px x 240px [w x h]

## Would you like to work on this
Too easy, would push it up as a beginner issue

**Comment by samyakbvs** [comment]
claiming
