### ISSUE TITLE
Lightbox grid gallery is appering twice

### ISSUE THREAD

**Issue by awesometushar000** [fossasia/gci17.fossasia.org#172]
### Expected results
It should not appear twice.

### Actual results
It shouldn't appear twice.

### Steps to reproduce the issue
visit gci website

## Would you like to work on this
yes as a gci task

**Comment by abishekvashok** [comment]
@awesometushar000 I think that was intentional. Can you find something to display there?

**Comment by nzec** [comment]
@awesometushar000 It was intentional. Please close this now!
