### ISSUE TITLE
Travis: Change the size of the images to 240 x 240

### ISSUE THREAD

**Issue by dilpreetsio** [fossasia/gci17.fossasia.org#179]
![](https://user-images.githubusercontent.com/8947010/33717206-10eafcdc-db7f-11e7-802c-da1fd8650772.png)

Change the size of the images listed in the image to 240 x 240

**Comment by awesometushar000** [comment]
https://travis-ci.org/fossasia/gci17.fossasia.org/jobs/313342013#L686
