### ISSUE TITLE
Issue with Alignment in Contributors portion.

### ISSUE THREAD

**Issue by Jeewal** [fossasia/gci17.fossasia.org#186]
### Expected results
Properly aligned contributors portion

### Actual results
![image](https://user-images.githubusercontent.com/34208541/33766765-14382ab8-dc47-11e7-8505-b3725339383d.png)

## 
I would like to work on this

**Comment by Jeewal** [comment]
@ms10398  I am going to work on this.

**Comment by abishekvashok** [comment]
@Jeewal I made some changes in #187.

**Comment by Jeewal** [comment]
So the Issue is resolved it seems ! Great. I'll choose another issue to work on then. :)    @abishekvashok :+1:
