### ISSUE TITLE
Cant find GCI task to improve tree

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/gci17.fossasia.org#20]

**Comment by YashKumarVerma** [comment]
i have made recommendations but unable to find the task ?

**Comment by mariobehling** [comment]
If there are no more tasks, then tasks in this category are finished. We need help with our real world projects as well. Please check out http://github.com/loklak for example. Thank you.

**Comment by YashKumarVerma** [comment]
thanks for reply sir.
