### ISSUE TITLE
The social media links are added two times

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/gci17.fossasia.org#211]
### Expected results
one of them is removed

### Steps to reproduce the issue
edit and delete the code for one

## Would you like to work on this
Yes

**Comment by samyakbvs** [comment]
Those links aren't required

**Comment by ParthS007** [comment]
@samyakbvs Please close this Issue , if it's resolved 👍

**Comment by nzec** [comment]
Yes. Please close this!

**Comment by abishekvashok** [comment]
Updates?
