### ISSUE TITLE
Change "App Sections" to use FOSSASIA Android App 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#212]
There are two app sections on the site. Change the sections to cover two FOSSASIA Android apps.

Instead of the placeholder app images create a high quality app image of a FOSSASIA app and add relevant text and links in one section.

![screenshot from 2017-12-09 18-35-08](https://user-images.githubusercontent.com/1583873/33797897-f6af5330-dd0f-11e7-9c93-dfe42b04a6f0.png)

**Comment by 0x48piraj** [comment]
I'm on it @mariobehling, I was going to file an issue on this :wink: 
As the task requires quality images, I will take some time. :+1: 

> **Note :** Please don't start working or make a **PR** without asking me, It's a kind request. I have suffered from this, **three** times!

**Comment by duttaditya18** [comment]
I am starting to work on this.

**Comment by ParthS007** [comment]
@0x48piraj Update your status. Thanks 👍

**Comment by nzec** [comment]
@ParthS007 As 0x48piraj is taking too long. I am starting to work on this!

**Comment by 0x48piraj** [comment]
I am working on this @duttaditya18 , have made one high-res image, working on the second.
Also, the site got updated, and this template got deleted. _(Guys should see all the issues, before hooking any issue.)_

> If you have done it, or started it. Please go on! :tada:
