### ISSUE TITLE
Make the drop down menu red on scroll over same as fossasia.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#213]
The scroll down item that is on "scroll over" should be red same as on http://fossasia.org

![screenshot from 2017-12-09 18-37-43](https://user-images.githubusercontent.com/1583873/33797912-3a59ecd0-dd10-11e7-8f77-08420f80f638.png)

**Comment by nzec** [comment]
On it!

**Comment by kol4k** [comment]
Like this?
![captureitplus636485124706873364](https://user-images.githubusercontent.com/19734061/33802913-6d882a36-ddb5-11e7-9343-b37b90f7eb23.png)

**Comment by nzec** [comment]
@kol4k Go on!

**Comment by kol4k** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/229 added scroll effect

**Comment by nzec** [comment]
This is fixed. Please close this.
