### ISSUE TITLE
Adding Danger

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci17.fossasia.org#221]
### Expected results
- Like last year, a friendly bot replies to new Pull Requests telling the author how to improve it

### Actual results
- There isn't such a thing in place

### Steps to reproduce the issue
- Open a PR

## Would you like to work on this
- Of course!

## How to do this
- [x] PR adding a Dangerfile to make the bot work. This PR can be merged while we wait for the second part. (https://github.com/fossasia/gci17.fossasia.org/pull/222) 
- [ ] PR adding Danger to Travis CI, as the GitHub application doesn't seem to work. (In progress)

<details>
<summary>Archived</summary>

- [x] Someone with admin access to the organization (like @mariobehling) has to [add the Danger app to this repo](https://github.com/apps/danger/installations/new).
</details>

**Comment by m1guelpf** [comment]
It seems like the Danger app is having some problems when processing the PR, gonna revert to the good ol' Travis way.

**Comment by abishekvashok** [comment]
Ping @fossasia/website-admins
