### ISSUE TITLE
Added the Fossasia Git CGI17 Issue information

### ISSUE THREAD

**Issue by kol4k** [fossasia/gci17.fossasia.org#233]
### Expected results
Added the Fossasia Git CGI17 Issue information with the Github API
### Actual results
There's no place for API Issue Github
### Steps to reproduce the issue
add API with Ajax

**Comment by abishekvashok** [comment]
@kol4k I can't get you

**Comment by ParthS007** [comment]
@kol4k Please explain in detail what you want to implement. Thanks 👍

**Comment by 0x48piraj** [comment]
@kol4k Help us!

**Comment by 0x48piraj** [comment]
@ParthS007 I think we should close this, as @kol4k is not responding.

**Comment by kol4k** [comment]
Sorry for a long response, can see in previous GCI web.
