### ISSUE TITLE
Some Mentors Are Missing from Page

### ISSUE THREAD

**Issue by niranjannitesh** [fossasia/gci17.fossasia.org#242]
### Expected results
Already having 11 mentors listed on the page.

### Actual results
Now only 5 are listed.

## Would you like to work on this
No, Because I had already added 8 extra but now some pull request had deleted the list.

**Comment by anshumanv** [comment]
Mentors have been moved to a separate page - https://gci17.fossasia.org/mentors.
Hence main page only displays a few of them
