### ISSUE TITLE
Align blog posts properly

### ISSUE THREAD

**Issue by anshumanv** [fossasia/gci17.fossasia.org#243]
### Expected results
The blogs should be correctly alligned
### Actual results
![image](https://user-images.githubusercontent.com/21009455/33805113-08db1cbe-ddd9-11e7-9ae1-7c96712ecb38.png)

### Steps to reproduce the issue
Visit https://gci17.fossasia.org/#student-blog
## Would you like to work on this
No, Open for students

**Comment by abishekvashok** [comment]
I can find that when I delete the div that contains the 2nd last blog post of the 2nd row, it is all fine.

**Comment by duttaditya18** [comment]
@anshumanv On it!
@abishekvashok Please work on some other issue.

**Comment by anshumanv** [comment]
Cool @abishekvashok, please send a PR for the fix. :smile:

**Comment by abishekvashok** [comment]
@anshumanv but I can't really find out why, can you give me some outputs?

**Comment by anshumanv** [comment]
Outputs as in? What can I help you with?

**Comment by nzec** [comment]
@abishekvashok I think this will be fixed if a div with class `.row` would be added after every 3 people.

**Comment by anshumanv** [comment]
Yea mostly it's due to improper rows.

**Comment by Ploypiti** [comment]
Guess it was because of long post titles so the margin of the **post title div** cause the post below to slides to the right, I tried removing the margin of `image-tile.outer-title.text-center` and it worked pretty well. **[Screenshot](https://ibb.co/m2w1h6)**

**Comment by anshumanv** [comment]
Looks fine to me, please send a PR and see if fixes it, thanks.

**Comment by nzec** [comment]
@Ploypiti Looks cool!
