### ISSUE TITLE
Menu bar not working

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#249]
### Expected results
When you go to students page and click welcome tab welcome section in the home page must be shown.
### Actual results
When you go to students page you can't to come again to home page using menu bar.
And other menu bar buttons are same.
### Steps to reproduce the issue
Give correct link in to menu bar buttons, If you click mentor tab added "#mentors" to the URL. It works when you in home page. If you in another page like students page just click mentor tab you will not come for home page.
## Would you like to work on this
Yes

**Comment by duttaditya18** [comment]
On it!
