### ISSUE TITLE
Substitute Gnome activities with FOSSASIA relevant activities

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#25]
Currently the what can i do answers are related to GNOME. Please substitute this with FOSSASIA relevant activities. You can take ideas from Code-In for example.

**Comment by mariobehling** [comment]
Actually, we have so many real projects. This project should be deprecated.

**Comment by abishekvashok** [comment]
@mariobehling so you mean we'r gonna see the last of whatcanidofor.fossasia.org
