### ISSUE TITLE
Menu Bar options don't work after we click see more

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/gci17.fossasia.org#254]
### Expected results
Clicking on any option in the menubar at https://gci17.fossasia.org/students should lead normally to the page expected.

### Actual results
Menubar won't work on pages like https://gci17.fossasia.org/{attribute}
Due to single page design and anchor references.

### Steps to reproduce the issue
Go to https://gci17.fossasia.org/students or https://gci17.fossasia.org/mentors 
and try menubar

## Would you like to work on this
No, GCI Students grab this one.

**Comment by samyakbvs** [comment]
claiming

**Comment by supunTE** [comment]
I said it. https://github.com/fossasia/gci17.fossasia.org/issues/249

**Comment by duttaditya18** [comment]
On it!
