### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/gci17.fossasia.org#255]
### Expected results
We should have a favicon

### Actual results
No favicon on Chrome 62.0.3202.94, Windows 10

![image](https://user-images.githubusercontent.com/21199234/33819835-7b78df74-de72-11e7-9b04-b54054b5af5e.png)

## Would you like to work on this
No

**Comment by YashKumarVerma** [comment]
working on it @aashutoshrathi . Thanks for the issue you raised.

**Comment by supunTE** [comment]
Can I work on this?

**Comment by abishekvashok** [comment]
Sure

**Comment by ParthS007** [comment]
@STEdirisuriya This is issue is resolved by @YashKumarVerma
