### ISSUE TITLE
Improve Fossasia GCI 2017 website

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/gci17.fossasia.org#269]
**This refers to the task [Website: Let's build the FOSSASIA Google Code-In website together and add a feature](https://codein.withgoogle.com/tasks/5728573547610112/?sp-organization=6237166344601600&sp-is_beginner=False)**

### Expected results

- Bugs Fixed
- Improved looks and feels
- Important features added
- Unnecessary placeholders removed **AND**/**OR**
- Replace some placeholders with more appropriate features
- Mentors/Contributors/Students section improved

### Steps to reproduce the issue

- [x] Bouncing Effect of arrow on the header slider like [This](https://codepen.io/dodozhang21/pen/siKtp)
- [ ] Improve image quality of header slider background (the map image) to higher resolution
- [x] Align the student projects section to center
- [x] Zoom and display personal info/motto when hovering on the Mentors, Contributors, and Students section like the[ Fossasia summit site](https://2016.fossasia.org/) and this theme
- [x] Add visible border to separate Mentors, contributor, and students section *or use different bg color*(gray, white, gray)
- [x] add *How can I be a contributor?* button to the contributors section, when user hovers their mouse the pop-up will appear & displaying info
- [x] Replace *'Foundry is a remarkably complete template...'* with something else about students
- [x] Add black transparent cover and white text displaying info about student projects, eg. what is it for and who developed it.
- [x] Color switch on *more* button hover
- [x] Fix *Thank you for contributing* section (Align to the middle)
- [x] Change *Fossasia in social Media* and *Fossasia based in Asia* BG (replace with actual image from Fossasia Flickr)
- [x] Replace *2008* placeholder block with participation rate
- [x] Replace *53 Hopetoun Rd. (placeholder)* with other feature (I don't know what is it yet, open to suggestion!)
- [x] Replace the watch showcase with tasks category and image to encourage new participators
- [x] Rearrange blog, remove blank space, change to ascending layout (most recent on top) and add the date to the post excerpt. In case the post title is to long cut to 8 words and add ... instead
- [x] Replace Videos from Students section with original theme's video section then change the background to white or add border to prevent confusion with blog section
- [x] Fix facebook embed section (width)

## Would you like to work on this
Yes! However, helps will be needed and suggestions are always welcome 👌

**Comment by vaibhavsingh97** [comment]
Hi @Ploypiti Awesome work! Now you had figured so many issues so you can start fixing the same. Some issues I wanna Discuss:
1. As you mentioned in Point 4 `Zoom and display personal info/motto when hovering on the Mentors, Contributors, and Students section like the Fossasia summit site and this theme`. You can add a dummy placeholder. Nice Idea 👏 
2. In Point 5, ` Add visible border to separate Mentors, contributor, and students section or use different bg color(gray, white, gray)`. It's already sperated 🤔 . Can you please descibe more what you wanna add to look more promising. 😄 
3. `Remove all unnecessary placeholder`. Please don't remove as this helps new contributor to add content If they don't know anything.

**Comment by Ploypiti** [comment]
This is what I mean (screenshot uploaded)
https://ibb.co/dvdCLG

**Comment by anshumanv** [comment]
Looks good @Ploypiti, go for it.
Not sure about removing removing placeholders though.

**Comment by Ploypiti** [comment]
@vaibhavsingh97 What do you mean by _add content If they don't know anything_?

**Comment by 0x48piraj** [comment]
@Ploypiti Have a look at it.
https://github.com/fossasia/gci17.fossasia.org/pull/368

**Comment by nzec** [comment]
1st Point was fixed.

**Comment by supunTE** [comment]
Please see this - https://github.com/fossasia/gci17.fossasia.org/issues/363 . I think some of issues you mention there are resolved in my issue.

**Comment by sandeepyadav097** [comment]
Added a popover for How can I contribute point number 6.
@Ploypiti have a look at #456

**Comment by nzec** [comment]
@ParthS007 @Ploypiti This was not wholly fixed. Please reopen this.

**Comment by ParthS007** [comment]
@duttaditya18 please don't write `fixes#issueno.` until the issue is completely fixed otherwise it will be closed automatically.

**Comment by sandeepyadav097** [comment]
Added a popover for How can I contribute point number 6.
@Ploypiti have a look at #456

**Comment by Ploypiti** [comment]
Only 1 point remaining so lemme close this..?

**Comment by nzec** [comment]
@Ploypiti Damn! That took time.

**Comment by nzec** [comment]
>@duttaditya18 please don't write fixes#issueno. until the issue is completely fixed otherwise it will be closed automatically.

@ParthS007 I did not write that.
