### ISSUE TITLE
Add documentation for running the website locally

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/gci17.fossasia.org#273]
### Expected results
A documentation for installation and running the website locally
- [x] For installation in Windows
- [x] For installation in Linux
- [x] For installation in MacOS

**Comment by vaibhavsingh97** [comment]
You can send multiple PR to solve this issue

**Comment by rupav** [comment]
@akshatnitd @vaibhavsingh97 claiming installation steps in windows.

**Comment by supunTE** [comment]
Please add this for Windows, I need help for it.

**Comment by rupav** [comment]
@akshatnitd @anshumanv Please review the PR.

**Comment by anshumanv** [comment]
Reopening since instructions only for windows are present.

**Comment by FUTC-Coding** [comment]
Claiming installation steps for linux

**Comment by FUTC-Coding** [comment]
#303

**Comment by nzec** [comment]
Claiming for MacOS!

**Comment by nzec** [comment]
@anshumanv @vaibhavsingh97 Check out #341
