### ISSUE TITLE
The section below Pitch us isn't correctly aligned

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/gci17.fossasia.org#275]
### Expected results
The section is aligned 
### Actual results
They are unaligned
### Steps to reproduce the issue
Resize the incorrect images
## Would you like to work on this
yes\

**Comment by anshumanv** [comment]
Please fill the Issue template correctly.

**Comment by samyakbvs** [comment]
@anshumanv how should I resize the image(s) they are taken from the net

**Comment by anshumanv** [comment]
Which image?
Please add screenshots of the problem too, if possible.

**Comment by samyakbvs** [comment]
![screen shot 2017-12-12 at 7 48 27 pm](https://user-images.githubusercontent.com/34275800/33889222-77fcdee6-df75-11e7-963c-3e160b3e8e62.png)
This was the problem @anshumanv but I guess I have fixed it in my PR now

**Comment by nzec** [comment]
I don't think this is required. Please close this.
