### ISSUE TITLE
Student's profile Facebook link use github username data instead

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/gci17.fossasia.org#288]
### Expected results
Correct facebook username
### Actual results
Facebook icon that should link to facebook link use this code `<a href="https://facebook.com/{{student.github}}" class="icon-a">` which should be `student.facebook`, this cause linking to wrong profile or 404 error 😱 
### Steps to reproduce the issue
Change to `student.facebook`
## Would you like to work on this
Yes

**Comment by ParthS007** [comment]
Closing with reference to #289
