### ISSUE TITLE
Remove highlights in the language selector window that opens up.

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/gci17.fossasia.org#3]
<img width="715" alt="screen shot 2015-12-16 at 8 38 34 am" src="https://cloud.githubusercontent.com/assets/4545925/11830992/6e09c33c-a3d0-11e5-8be1-1a17c3d084f2.png">

**Comment by shashank-sharma** [comment]
I simply edited the .css file which was jquery.uls.css by removing border and adding outline colour transparent with outline style none and now its working fine. Here is my pull request (https://github.com/fossasia/whatcanidofor.fossasia.org/pull/12).
