### ISSUE TITLE
Create a separate page with a map showing all FOSSASIA GitHub members

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#302]
GitHub has a number of APIs. Research how members of an organization can be displayed on a map and implement it on a separate page.

**Comment by abishekvashok** [comment]
Members list can be got using Github API, ref: https://developer.github.com/v3/orgs/members/#members-list
Then for each user using the user api endpoint, ref: https://developer.github.com/v3/users/ the location can be extracted, and then be displayed on an Open Street Map.

**Comment by 0x48piraj** [comment]
Many don't put their locations, and strings instead of them. eg. (127.0.0.1, Planet Earth, list goes on ...)
We'll have to handle that! :+1: 
Ping : @mariobehling @abishekvashok
