### ISSUE TITLE
Change the navbar so that it is set to be transparent at first and change to white if scrolldown detected.

### ISSUE THREAD

**Issue by ChenNuode** [fossasia/gci17.fossasia.org#305]
Hi this is for a GCI task, Im trying to make the nav bar of the FOSSASIA GCI site consistent with the https://fossasia.org/ site

Can i choose to make this improvement for the site?

**Comment by ChenNuode** [comment]
Also can i change the navbar such that it shows up in the mentors section?

<img width="500" alt="screen shot 2017-12-14 at 4 17 54 pm" src="https://user-images.githubusercontent.com/23238289/33982142-6151875c-e0ea-11e7-8fa4-627c0768b5df.png">

**Comment by kubami9** [comment]
@ChenNuode I think it's great idea! 😃

**Comment by ParthS007** [comment]
@ChenNuode  Please close this or update your status if not resolved 👍
