### ISSUE TITLE
Delete unwanted spaces on blog section 

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#311]
### Expected results
Remove spaces between images
### Actual results
No spaces
![screenshot from 2017-12-15 12-00-20](https://user-images.githubusercontent.com/33794760/34029650-86c140dc-e161-11e7-883a-5eb81a712fe4.png)

## Would you like to work on this
Yes

**Comment by nzec** [comment]
#315 gets ya!
