### ISSUE TITLE
One photo for two.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#320]
### Expected results
Change the photo
![issue](https://user-images.githubusercontent.com/33794760/34060265-e4bbe1a4-e208-11e7-893d-7c10edac95f1.JPG)
### Actual results
There are two students who have same photo.
### Steps to reproduce the issue
Remove broken one.

Samayak Jain or Hasalu Botheju must change his photo!

**Comment by 0x48piraj** [comment]
@STEdirisuriya Have a look :+1: 

https://github.com/fossasia/gci17.fossasia.org/pull/358
