### ISSUE TITLE
Make codes simple and short.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#325]
### Expected results
Make codes simple and short.
### Actual results
Code files are too longer now.
### Steps to reproduce the issue
Use simple codes. 
Make sections separately from "index.html". 
Remove unwanted tags. 

(Ex:- For <-example-img src="...... jpg"></img>
      Just use <-example-img src="......jpg"/>

For <-example-i class="ti-twitter-alt"></i>
      Just use <-example-i class="ti-twitter-alt"/>)

*I use there '-example-' because, If it is not the code going to appear. Remove it when designing
## Would you like to work on this
I am working, But anyone can work on this.

**Comment by YashKumarVerma** [comment]
can you please elaborate the topic ?
