### ISSUE TITLE
Building new website

### ISSUE THREAD

**Issue by hemanthsavasere** [fossasia/gci17.fossasia.org#33]
Hi @mariobehling,
I want to take up the task of creating the website rebuilding it from scratch by myself.

**Comment by Witus13** [comment]
There is a task like that?

**Comment by jigyasa-grover** [comment]
@hemanthsavasere  It'd be great if you could send in patches to enhance the present website, in order to build one from scratch you could always take up that task independently. Thanks !

**Comment by hemanthsavasere** [comment]
thanks @jig08
