### ISSUE TITLE
Add Geolocation of GCI mentors in map 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/gci17.fossasia.org#332]
### Expected results
Location of all GCI mentors should be present in maps which are already added to Website.

### Actual results
Presently, Few mentor's location is updated in maps.

**Comment by ParthS007** [comment]
@abishekvashok Have a look at this 👍

**Comment by supunTE** [comment]
From where we can find there locations?

**Comment by shikhar-scs** [comment]
@ParthS007 Actually in the mentors.yml file only 3 mentors have mentioned their lat and lng and all 3 of them already reflect on the map. Similarly, in the students.yml file only 8 students have done the same and they too, do reflect on the map. Thus, the information part is in complete, not the mapping.

P.S. By map here i mean the community connect map.

**Comment by abishekvashok** [comment]
@STEdirisuriya @shikhar-scs try to ping them but don't try to disturb them :)

**Comment by shikhar-scs** [comment]
@abishekvashok 
In total there are 23 mentors and 31 students listed and we need info on 20 mentors and 23 students. So is there any way where we can broadcast a common message to all of them to update their respective infos (maybe slack or any IRC channel). Because contacting everyone individually might take up a lot of time.

**Comment by abishekvashok** [comment]
@shikhar-cs contacting individually would only work, broadcasting on gitter might work but no guarentee. You can try your own method.

**Comment by shikhar-scs** [comment]
@abishekvashok Can you send me the link for joining gitter plz.

**Comment by abishekvashok** [comment]
@shikhar-scs gitter.im/fossasia/fossasia

**Comment by Ploypiti** [comment]
@ParthS007 Can we just get their location from Github profile and use some tool like [this one](https://www.latlong.net/) to get the lat & long and add the location without asking them?

**Comment by abishekvashok** [comment]
@Ploypiti sure, but remember some have locations like 127.0.0.1 {random strings}

**Comment by shikhar-scs** [comment]
@Ploypiti Many have just mentioned their country on their github profile, a few links are broken (404) and at most a state is mentioned. Wouldnt that be too vague to add ? 
If not then we can do so I guess.

**Comment by akshatnitd** [comment]
It is not necessary to add very exact information like street address. The main goal of the geolocation project is to get a nice overview of locations of participants city and country-wise.
