### ISSUE TITLE
Add a pop-up window

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#333]
### Expected results
Add a pop-up when starting the web site for welcome visitors.

### Steps to reproduce the issue
Add code for make a pop-up

## Would you like to work on this
Yes, I'm working on this.

**Comment by 0x48piraj** [comment]
I think, the welcome page is good enough.
It will probably, change the order of site, will degrade the quality.

**Comment by abishekvashok** [comment]
@STEdirisuriya a popup window on start can lower your page's quality, better not to do so :)

**Comment by supunTE** [comment]
Why?
