### ISSUE TITLE
Make the website

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#34]
Suggestions:
Modify the existing theme to fossasia design
Add:
- [ ] Mentors Section
- [ ] Students Section

They both should be dynamic, ie, we should make use of jekyll as done for the gci16 webiste
ref: https://github.com/fossasia/gci16.fossasia.org/

This will be a building block for students who can then do the tasks:
1. Add yourself to the gci17 website
2. Add a mentor to the gci17 website

What do you think?

**Comment by abishekvashok** [comment]
Working on it...

**Comment by idealadarsh** [comment]
@abishekvashok Are you creating both sections?

**Comment by abishekvashok** [comment]
we can split if you would like @idealadarsh

**Comment by mariobehling** [comment]
Please don't change the theme. The theme is awesome. FOSSASIA's theme should also get an overhaul soon.

**Comment by abishekvashok** [comment]
👍
