### ISSUE TITLE
Website Load Time : Too Many requests on load ~330

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/gci17.fossasia.org#344]
### Expected results
The website load time must be reduced, images should load when in viewport

### Actual results
Images load with main page content.

### Steps to reproduce the issue
Implement "lazy load" to load images when needed.

## Would you like to work on this
Yes !

**Comment by abishekvashok** [comment]
@YashKumarVerma pls use Google insights which provides a better comparison.

**Comment by YashKumarVerma** [comment]
[![Screenshot_2017_12_18_19_51_45](https://thumb.ibb.co/f1mw5R/Screenshot_2017_12_18_19_51_45.png)](https://ibb.co/f1mw5R) [![Screenshot_2017_12_18_19_49_51](https://thumb.ibb.co/fUEG5R/Screenshot_2017_12_18_19_49_51.png)](https://ibb.co/fUEG5R)
