### ISSUE TITLE
Add travis and other CI tests

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#35]
Travis CI is a great solution to check the PR and merge with confidence.
We should integrate it with some tests.

**Comment by gabru-md** [comment]
Travis and testing can be added after the website work has begun.
There is a task in GCI regarding creating GCI-17 FOSSASIA's website .
Please refer to that if you want to work on it.

**Comment by abishekvashok** [comment]
Flag this as not required now then @gabru-md or close this issue

**Comment by harshit98** [comment]
@gabru-md I would suggest adding Travis CI just like other FOSSASIA repositories before proceeding on website work. :)

@abishekvashok Would you like to set up Travis CI in this repository?

**Comment by abishekvashok** [comment]
@harshit98 sure

**Comment by gabru-md** [comment]
Okay! @harshit98 
:smile:

**Comment by jigyasa-grover** [comment]
@abishekvashok Pls go ahead with setting up TravisCI and if possible, take up the corresponding task on the GCI dashboard as well for brownie points, Cheers 🎉

**Comment by abishekvashok** [comment]
@jigyasa-grover sure.

**Comment by abishekvashok** [comment]
@jigyasa-grover #55 does it.

**Comment by abishekvashok** [comment]
@jigyasa-grover also don't forget to enable it in the travis ci dashboard.

**Comment by abishekvashok** [comment]
@fossasia/fossasia-gci can someone enable travis CI building in the dashboard, it's still not enabled yet.
