### ISSUE TITLE
Add mentors to the mentors section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#36]
Please add a mentor to the mentors section.

**Comment by abishekvashok** [comment]
Working on it...

**Comment by abishekvashok** [comment]
@mariobehling #46 adds you.

**Comment by abishekvashok** [comment]
@mariobehling you got the data of the google form responses where mentors apply right? Can you provide them here, I think that will benefit the new contributors. What do you think?

**Comment by ba11b0y** [comment]
Yes @abishekvashok , but you most probably will be requiring an image which was not submitted in the google form.

**Comment by abishekvashok** [comment]
But we could ask them from that list :)

**Comment by anshumanv** [comment]
Here's the team - https://github.com/orgs/fossasia/teams/fossasia-gci
Pick any mentor from it.

**Comment by supunTE** [comment]
I added two

**Comment by sandeepyadav097** [comment]
@anshumanv the link you provided has all the mentors?
I would like to add some

**Comment by ParthS007** [comment]
@sandeepyadav097  If you want to add mentor, you can add us to [team ](https://fossasia.org/team) section here in Developers section 👍

**Comment by ParthS007** [comment]
closing it as all mentors are added 👍
