### ISSUE TITLE
Big issue with social media section. Please see this; this issue is updated.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#361]
### Expected results
Make FB page full showing.

### Actual results
In social media section
![pro](https://user-images.githubusercontent.com/33794760/34148936-5ebe49f2-e4c9-11e7-9d9f-3fb848a27461.png)
See Twitter and G+ pages are showing properly, But FB page only showing a part of it, there is a
half-cut.
![pro2](https://user-images.githubusercontent.com/33794760/34149191-4b10733e-e4ca-11e7-8903-7dfa509f2f07.png)
Part of that not showing. see this screen-shot.

### Steps to reproduce the issue
Make that part smaller or page bigger. Or you can make new section with new method.

## Would you like to work on this
You can work on this.

**Comment by shikhar-scs** [comment]
I am working on this and will soon post a PR

**Comment by shikhar-scs** [comment]
Also note that these sections aren't responsive. Ill work on that too.

![ss](https://user-images.githubusercontent.com/25258877/34150929-d51f8a10-e4cf-11e7-8580-2f392d2d6561.png)

**Comment by supunTE** [comment]
@shikhar-scs OK. Sure work on this

**Comment by shikhar-scs** [comment]
The problem of the issue has been fixed. Now I'm working on responsiveness.

**Comment by nzec** [comment]
Fixed now. Please close this.

**Comment by shikhar-scs** [comment]
@STEdirisuriya close this now please

**Comment by supunTE** [comment]
No. it is yet. see - 
![issue yet](https://user-images.githubusercontent.com/33794760/34224755-f8768584-e5e9-11e7-936c-7abad1d15aa6.png)
![issue yet 2](https://user-images.githubusercontent.com/33794760/34224756-f8e91220-e5e9-11e7-9226-8016fd0353e3.png)
Now issue had improved.

**Comment by supunTE** [comment]
now it's OK
