### ISSUE TITLE
One of students projects' link is broken!

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#362]
### Expected results
Make it correct.

### Actual results
One of student projects' link is broken in Students Projects Section.
![st](https://user-images.githubusercontent.com/33794760/34151978-09e55ccc-e4d3-11e7-96b1-3dda25efe698.png)
Doon International School project by @YashKumarVerma is not working.
See below picture that came after I clicked that project.
![st2](https://user-images.githubusercontent.com/33794760/34152050-41287d4a-e4d3-11e7-9ece-221720cee1a6.png)

### Steps to reproduce the issue
Add correct link to that project or, remove that project.

## Would you like to work on this
@YashKumarVerma Please add correct link.

**Comment by 0x48piraj** [comment]
Ping @YashKumarVerma :+1:
