### ISSUE TITLE
Fix errors and bugs! And make improvements.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#363]
### Expected results
- Improved looks
- Fixed error
- Improved sections
- Nice looked site with more animations 

### Steps to reproduce the issue
- [ ] Add a welcome box. [like this.](https://codepen.io/MarcMalignan/pen/xByvJ)
- [ ] Remove unwanted tags.
(Ex:- For `<img src="......jpg"></img>`  Just use `<-example-img src="......jpg"/>`
For `<i class="ti-twitter-alt"></i>` Just use `<i class="ti-twitter-alt"/>`)
- [x] Add thanks for contributors box after contributors section. 
- [x] Videos from students section make separately from `index.html`. I means add it into _data folder like `blogs.yml`. For the now, it is in `index.html`. See code of `index.html`. And make a `videos.yml`. 
- [x] Add a paragraph about how to adding video to the `videos.yml` on `README.md`.
- [ ] Add a link to the videos sections on menu.
- [ ] Add animation when holding on the button to _"**More** button in mentors section,**More** button in students section"_ like the buttons in the welcome section. [see example](https://user-images.githubusercontent.com/33794760/34154187-a508a5b8-e4da-11e7-9c10-972ef527fc2a.png)
- [ ] Make contributors section smaller students and mentors section. Add "More" button to there. (For see all contributors click more button.)
- [ ] Remove [this](https://user-images.githubusercontent.com/33794760/34154465-9a559a8a-e4db-11e7-9313-c995ad28f599.png) mark `:)` on end of the sentence. (A combination of small mistakes make a big issue) 
- [x] Map is not showing now. [see this](https://user-images.githubusercontent.com/33794760/34154676-5c3951dc-e4dc-11e7-974a-6589ca18fbfb.png)
- [ ] Add quotations for mentors, students like [this](https://user-images.githubusercontent.com/33794760/34173786-a24e133e-e51c-11e7-9344-161e0f711cf1.png). ([see more](https://gci15.fossasia.org/#students)...) 
- [x] Add animations to the blogs section.
- [x] Add animations to the video section.
- [ ] Add a logo of GCI on the top of the site.

## Would you like to work on this
I am working, I need more help

**Comment by nzec** [comment]
I say no for the welcome box.

**Comment by supunTE** [comment]
That's improve attraction of visitors.

**Comment by abishekvashok** [comment]
Please don't add it, it will lower the page ranks.

**Comment by supunTE** [comment]
OK

**Comment by 0x48piraj** [comment]
@abishekvashok is absolutely right, also the link issue will affect in **SEO Ranking**

**Comment by nzec** [comment]
@STEdirisuriya 10th point was fixed by #378

**Comment by supunTE** [comment]
I am working 12th point. Add animations to the blogs section. I want to work on it alone.

**Comment by duttaditya18** [comment]
Okay,.

**Comment by harshit98** [comment]
I'm closing this issue. If something has been missed, create a separate issue for it.
