### ISSUE TITLE
Github Repos in Website

### ISSUE THREAD

**Issue by NaviRocker** [fossasia/gci17.fossasia.org#365]
It would be great if Fossasia's Repositories are on the Website. So that If a Visitor likes it, He/She can start from there itself

**Comment by 0x48piraj** [comment]
I personally think, there's no need of that @naveentherocker 
Preferably, we should use the button "**Explore the Website**" to link it to the **FOSSASIA Organisation** instead of linking it to the mentors section. That will cause the visitor to elegantly visit the FOSSASIA Repositories :wink:

**Comment by NaviRocker** [comment]
Check the Link @0x48piraj https://naveentherocker.github.io/gci17.fossasia.org/repos.html
This is what I have made for now. Have a look at it. It is not linked to the Mentor's Section.

**Comment by 0x48piraj** [comment]
@naveentherocker 
I think you just had linked it to https://github.com/fossasia.
But, an inline page is also good, or actually great :+1: 

I think you should **link it to the following button**, as it is going to mentors page which is not that cool.
![image](https://user-images.githubusercontent.com/5800726/34172432-0cd78e1a-e518-11e7-85c5-976ec4b2466d.png)

**Comment by NaviRocker** [comment]
Well If I linked to the button mentioned above, Is it fine then? @0x48piraj

**Comment by NaviRocker** [comment]
Changes committed @0x48piraj . 
Preview Link - https://naveentherocker.github.io/gci17.fossasia.org

**Comment by 0x48piraj** [comment]
That's what I wanted :tada:

**Comment by NaviRocker** [comment]
Splendid! So you can review it now #359
