### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci17.fossasia.org#38]
In last year's website, we used Jekyll for student, mentor and project listing to avoid breaking things, merge conflicts, etc.

This year, we should do it again :smile:

**Comment by jigyasa-grover** [comment]
@mariobehling ping.

**Comment by mariobehling** [comment]
If you want to implement Jekyll, then you need to implement it using the current design. Cheers.

**Comment by m1guelpf** [comment]
@mariobehling Will do when I finish current task 😄

**Comment by abishekvashok** [comment]
@mariobehling @jigyasa-grover can you include the git hook for jekyll then.
ref: https://jekyllrb.com/docs/deployment-methods/

That was done last year I guess.

**Comment by m1guelpf** [comment]
@abishekvashok Last year, we used Travis CI for that...

**Comment by abishekvashok** [comment]
That was for testing i guess. I think the hooks not needed now.

**Comment by m1guelpf** [comment]
@mariobehling @jigyasa-grover Opened https://github.com/fossasia/gci17.fossasia.org/pull/52

**Comment by jigyasa-grover** [comment]
@m1guelpf Cool !

**Comment by abishekvashok** [comment]
Seems like @AKostiv8 solved this.

**Comment by abishekvashok** [comment]
I think this can be closed @m1guelpf what do you think?
