### ISSUE TITLE
The are no images

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/gci17.fossasia.org#381]
### Expected results
Images not appearing
### Actual results
Images should appear

## Would you like to work on this
yes

**Comment by samyakbvs** [comment]
![screen shot 2017-12-20 at 8 51 32 pm](https://user-images.githubusercontent.com/34275800/34214243-e7e6fd4c-e5c7-11e7-8e15-753a78de27ad.png)

**Comment by the-codingninja** [comment]
Images are there you should check again

**Comment by samyakbvs** [comment]
No I checked again

**Comment by samyakbvs** [comment]
Also the images for mentors are missing

**Comment by samyakbvs** [comment]
claiming tp fix that too

**Comment by samyakbvs** [comment]
I am so sorry everyone they are there on my link without editing the code so they must be on the original site too. there must be some problem in my system
