### ISSUE TITLE
The google+ page is added two times

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/gci17.fossasia.org#388]
### Expected results
Delete one
### Actual results
The google+ page is added two times

## Would you like to work on this
yes

**Comment by shikhar-scs** [comment]
I fail to see rhis issue. Could you elaborate a bit more on this please.

**Comment by supunTE** [comment]
i say it on https://github.com/fossasia/gci17.fossasia.org/issues/361

**Comment by supunTE** [comment]
Close this issue now! @samyakbvs
