### ISSUE TITLE
Mantainers

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci17.fossasia.org#39]
Last year, we had a group of students who volunteered for mantaining this repository (https://github.com/orgs/fossasia/teams/gci16-maintainers). I think this year we should make another (if we do it before website notifications _explode_, better).

Of course, I offer myself :smile: 

WDYT @mariobehling @niccokunzmann?

**Comment by mariobehling** [comment]
Good idea, but we need to see some initial commits before assigning rights to students. Students should follow Best Practices (https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) and provide a test page and screenshot of their changes. I see that you did not do this yet at your last merged pull request. Therefore we will give students more time to get accustomed to the Best Practices.
