### ISSUE TITLE
Align students section.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#415]
### Expected results
Make a aligned students page with same size pictures.

### Actual results
Not aligned, Not same sized images.
![issnew](https://user-images.githubusercontent.com/33794760/34289323-fe134f48-e717-11e7-9e44-ec5581b88a65.png)
![issnew2](https://user-images.githubusercontent.com/33794760/34289324-ffabb570-e717-11e7-9867-360a8a9acf52.png)
![not](https://user-images.githubusercontent.com/33794760/34292154-a392c09a-e725-11e7-8512-dbb3e299bed2.png)

### Steps to reproduce the issue
I am trying to aligned those, but I need a help. All of students who not given a correct size image (240x240 px), _Please add those images on this issue with correct sizes_ (I'll make it) or _replace that correct sized image with your old image and send there a link of that PR_.

## Would you like to work on this
I am working, please give me your correct images or replace as above.
- @abishekvashok 
- @saarthakchats 
    Your pictures are smaller

**Comment by abishekvashok** [comment]
@STEdirisuriya be sure to do so

**Comment by Ploypiti** [comment]
@STEdirisuriya Use Photoshop to resize instead of asking for their photo.

**Comment by ParthS007** [comment]
@STEdirisuriya  Please update your status or close this if resolved 👍

**Comment by ParthS007** [comment]
@STEdirisuriya Please update your status or close this if resolved 👍
