### ISSUE TITLE
Add a back to "top button"

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#422]
### Expected results
Add a "back to top button" (floating one)

## Would you like to work on this
I am working.

**Comment by 0x48piraj** [comment]
Already present :+1: @STEdirisuriya

**Comment by supunTE** [comment]
No It's on bottom of page; I said about a not like that one, When we're scrolling we can see a back to Top button. @0x48piraj

**Comment by sandeepyadav097** [comment]
I would like to try it out @STEdirisuriya

**Comment by 0x48piraj** [comment]
@STEdirisuriya 

You meant a floating button ?

**Comment by duttaditya18** [comment]
@sandeepyadav097 Can I work on this?

**Comment by supunTE** [comment]
I am working on this @sandeepyadav097

**Comment by supunTE** [comment]
It's OK now.
