### ISSUE TITLE
Fix Render bug

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/gci17.fossasia.org#424]
### Expected results
Website without `---`

### Actual results
![](https://user-images.githubusercontent.com/5800726/34309046-081fcaa8-e776-11e7-82ea-275312b36dc6.png)
### Steps to reproduce the issue

Just browser to our **gci17** website.

## Would you like to work on this
Yep.

> Simply deleting `---` doesn't solves the issue.

#### Rendered page when simply deleting : 

![image](https://user-images.githubusercontent.com/5800726/34309772-d02cbf58-e779-11e7-8feb-3de739dd4060.png)

**Comment by ba11b0y** [comment]
Closed via #438
