### ISSUE TITLE
Adding languages step by step

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#445]
### Expected results
**Get together all! Show power of unity in all world including Asia. Make easily connected to all students and mentors...**
Adding languages around the world to site.
This issue is connected with this issue - https://github.com/fossasia/gci17.fossasia.org/issues/83

### Steps to reproduce the issue
- [ ] Translate installations files into more than 15 languages.
      - Sinhala added by @STEdirisuriya (Me)
      - Polish added by @kubami9  
      - French added by @Ploypiti 
- [ ] Translate paragraphs in index.html into more than 15 languages.
- [ ] Connect with jekyll for added languages into site. - [refer this]https://www.sylvaindurand.org/making-jekyll-multilingual/)
- [x] Until making to jekyll we have to give a method for translate it. So, add Google Translate Plug-in for site until it finished.
- [ ] Translate whole page into more than 10 languages.
- [ ] Add more languages into thank you contributing section.
- [ ] Add comments section for sharing ideas about site with more languages.
- [x] Add how to translate in README.md
## Would you like to work on this
Get together all! I am working on it with Sinhala language. Students help us for make translations. We will make it easier for adding translations. I need lot of help. This is a small step for big jump!

**Comment by gabru-md** [comment]
What kind of help do you need her  @STEdirisuriya ?
You were asking for it on Gitter

**Comment by supunTE** [comment]
We need help for translate page to other languages. I need help for that. I said it on this issue see. @gabru-md I need others contributions. They can translate files and make PRs and connect for this issue

**Comment by supunTE** [comment]
@kubami9 Thanks for help in this. Continue your job
