### ISSUE TITLE
Mentors not added to mentor section...

### ISSUE THREAD

**Issue by yashk0thari** [fossasia/gci17.fossasia.org#469]
### Expected results
Add them (one mentor for this issue)

### Actual results
not added mentors

### Steps to reproduce the issue
go to fossaisa's gci website
go to mentor section (not added mentors)

## Would you like to work on this
YES !!

**Comment by supunTE** [comment]
What for this issue?

**Comment by ParthS007** [comment]
All Mentors are added already
