### ISSUE TITLE
Removal of Dead link in "Loklak A sister Project" Section

### ISSUE THREAD

**Issue by sandeepyadav097** [fossasia/gci17.fossasia.org#479]
### Expected results
The changes will redirect to correct link
### Actual results
The redirection of the link is inappropriate.
## Would you like to work on this

Yupp

**Comment by sandeepyadav097** [comment]
Done

**Comment by abishekvashok** [comment]
Which PR@

**Comment by sandeepyadav097** [comment]
This one
