### ISSUE TITLE
Transalation

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/gci17.fossasia.org#505]
### Expected results
The website should be translated into at least 4 other languages
### Actual results
The website hasn't been translated even in one
## Would you like to work on this
Yes! Pls don't work on this issue without my consent

**Comment by kubami9** [comment]
Hello @samyakbvs! It's really cool that you'd like to help out with translating and actually there is already an issue with this task(s). Check it out #445. Let's do this all together so there won't be any misunderstandings and issues with translation methods. Cheers!

**Comment by vaibhavsingh97** [comment]
Fixed in https://github.com/fossasia/gci17.fossasia.org/commit/76d5d7cbe62affc2f2e957832f71677b8e0b076d
