### ISSUE TITLE
Indent all files

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#547]
### Expected results
Indent all files to improve quality.

### Actual results
Some files are not indented.

### Steps to reproduce the issue
Use tools like [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) for VS code,  [atom-beautify](https://atom.io/packages/atom-beautify) for atom.

## Would you like to work on this
Open, for claim New comers welcome to this.

**Comment by ParthS007** [comment]
Update your status @STEdirisuriya  👍

**Comment by abishekvashok** [comment]
@STEdirisuriya we can't afford this now. We can only do this after GCI as otherwise it will lead to conflicts of almost all forks.

**Comment by vaibhavsingh97** [comment]
@STEdirisuriya Let's this issue open for beginners/New commers.

**Comment by abishekvashok** [comment]
@vaibhavsingh97 as I mentioned it would cause a lot of conflicts if we do it all in one go. Can we update this to break it?

**Comment by vaibhavsingh97** [comment]
@abishekvashok Only somefiles are not indented and this repo is purely for learning so let students learn how to resolve conflicts 😉 
Moreover, I am always here to help

**Comment by abishekvashok** [comment]
@vaibhavsingh97 it's fine then :)

**Comment by supunTE** [comment]
@vaibhavsingh97 Thanks for helping! i opened it for new comers.
 @abishekvashok Thank you too

**Comment by STEdirisuriya** [comment]
I am indenting now index.html

**Comment by tanya-vedi** [comment]
Can I solve this issue?
