### ISSUE TITLE
Remove reduntant css files

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#558]
### Expected results

Only the css file which are used should be kept.

### Actual results

Reduntant and not needed css files are present.

### Steps to reproduce the issue

Go to the css folder of the website and see.

**Comment by YashKumarVerma** [comment]
working on it 🔥

**Comment by abishekvashok** [comment]
Sure @YashKumarVerma

**Comment by ParthS007** [comment]
@abishekvashok Please close this if resolved 👍

**Comment by abishekvashok** [comment]
@ParthS007 note yet. The PR is still to be merged. He was referencing this issue no: from his commit

**Comment by harshit98** [comment]
@YashKumarVerma Please refer PR no. here in which fix has been done. If your PR has been merged, @abishekvashok please close this issue.
