### ISSUE TITLE
Blogs and video sections not appearing correctly!

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#563]
### Expected results
Make it as earlier.

### Actual results
Not showing pictures of blogs and videos.
![erris](https://user-images.githubusercontent.com/33794760/34406576-d5e58244-ebdf-11e7-8f63-08f0351ad654.png)
![erriss2](https://user-images.githubusercontent.com/33794760/34406577-d6758b00-ebdf-11e7-8c57-1b22e4c94419.png)

### Steps to reproduce the issue
Check and resolve codes errors done by someone.

## Would you like to work on this
Yes I am working

**Comment by abishekvashok** [comment]
Open console and close. It will appear.

**Comment by supunTE** [comment]
Why?
You said website users to open console and close, No! Find a way for resolve it.
And I want to say it is not working after you said method too.
@abishekvashok

**Comment by divitsolanki** [comment]
it is just because of slow loading.

**Comment by ParthS007** [comment]
closing this as fixed in #627
