### ISSUE TITLE
Adding PWA Features to the Site

### ISSUE THREAD

**Issue by niranjannitesh** [fossasia/gci17.fossasia.org#571]
### Expected results
Should Load Faster
### Actual results
Loads Very Slowly
### Steps to reproduce the issue
Add Service Workers and Cashing
## Would you like to work on this
Yes.

**Comment by YashKumarVerma** [comment]
sure ! go ahead @niteshkumarniranjan . Feel free to ask for assistance if needed 😄

**Comment by harshit98** [comment]
@niteshkumarniranjan what's the status of this issue?

**Comment by niteshkumarniranjan** [comment]
@harshit98 for adding pwa features it requires HTTPS in the websites.
so, thats the reason. I had implemented the pwa features but it would require HTTPS.

**Comment by niranjannitesh** [comment]
@harshit98 I had completed my work and I will create an PR.
