### ISSUE TITLE
Student Projects - Hover text not visible

### ISSUE THREAD

**Issue by divitsolanki** [fossasia/gci17.fossasia.org#575]
### Expected results
On mouse hover - text should be visible

### Actual results
Text mixed with the background on mouse hover

### Steps to reproduce the issue
Need black overlay layer between text and image with opacity

## Would you like to work on this
Yes

**Comment by harshit98** [comment]
Hi @divitsolanki what's the status of this issue?

**Comment by ParthS007** [comment]
closing this as everything is working fine 👍
