### ISSUE TITLE
Add auto-deployment feature.

### ISSUE THREAD

**Issue by harshit98** [fossasia/gci17.fossasia.org#58]
Add auto-deployment feature. It should work as:
- Demo link should be generated easily.
- It will be easier for the mentors to review the pull requests.

**Comment by abishekvashok** [comment]
The format for the link is:
https://username.github.io/gci17.fossasia.org/

**Comment by 0x48piraj** [comment]
On it @harshit98 and @abishekvashok  :wink:

**Comment by harshit98** [comment]
I'm closing this issue, since there is already a format for the link present.
