### ISSUE TITLE
Add a asciinema section

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#602]
### Expected results
Collect ascii casts from students and make a asciinema section.

### Actual results
No section for this yet.

### Steps to reproduce the issue
Change codes

## Would you like to work on this
I am working on this!

**Comment by nzec** [comment]
Really cool idea! Do you think there will be many casts? I think it'd be empty.
@fossasia/fossasia-gci Need help!

**Comment by abishekvashok** [comment]
Hmm, it seems to be nice idea.

**Comment by supunTE** [comment]
no there will be lot of asciicasts @duttaditya18

**Comment by harshit98** [comment]
I think there is no need to add asciinema section. It will result in slow loading of website.
