### ISSUE TITLE
[bug] The menu bar get distorted on scrolling.

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/gci17.fossasia.org#608]
### Expected results
The icon should not float like that.

### Actual results
![image](https://user-images.githubusercontent.com/5800726/34441784-ff22d300-ece3-11e7-90e8-dde28d707a18.png)

### Steps to reproduce the issue
Hover to _**gci17.fossasia.org/activities**_

## Would you like to work on this

**Bug ? Yes !! :+1:**

**Comment by ParthS007** [comment]
@0x48piraj  I am not able to reproduce the issue, can you just recheck again by pulling latest changes. Thanks 👍

**Comment by 0x48piraj** [comment]
Okay, will check after those bug fixes are merged. :+1:

**Comment by 0x48piraj** [comment]
Yet there @ParthS007

**Comment by 0x48piraj** [comment]
Thanks @saarthakchats

**Comment by 0x48piraj** [comment]
Thanks @saarthakchats
Closing :+1:
