### ISSUE TITLE
Add thanks for contributing section

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#61]
Add thanks for contributing section to the website with multiple language support.

**Comment by abishekvashok** [comment]
Working on it.

**Comment by gabru-md** [comment]
Can you please tell what is "multiple language support". ?

**Comment by abishekvashok** [comment]
@gabru-md sure, just like last year's website we will display "Thank you for contributing" in a language, then with javascript after some seconds display it in another language.

**Comment by gabru-md** [comment]
That will be great!
Keep going
Cheers

**Comment by abishekvashok** [comment]
@gabru-md done in #62

**Comment by abishekvashok** [comment]
@naveentherocker let's be professional, it would be great if you could follow the best practises:
https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

I was working on it, and got a approved PR, but however you pushed in another solution and got my PR closed; It's okay since you are new, but next time on wards pls try not to collide with other,s comment on an issue, if you would like to work on it. Please follow the best practices. Cheers.

CC: @gabru-md @jigyasa-grover 
Ref #64, #62
