### ISSUE TITLE
[discussion] Why GCI'16 contributors are there ?

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/gci17.fossasia.org#614]
![image](https://user-images.githubusercontent.com/5800726/34442697-d336025c-ece9-11e7-8d54-f407fac8f400.png)

Ping : 
@vaibhavsingh97 @ParthS007 @ms10398  @harshit98 @anshumanv @YashKumarVerma @abishekvashok @STEdirisuriya @duttaditya18  @Ploypiti

**Comment by ParthS007** [comment]
@0x48piraj  It's just a link to previous year contributors, I don't think any discussion is needed 👍

**Comment by 0x48piraj** [comment]
@ParthS007 There should be this year's contributors. No ?
