### ISSUE TITLE
'ENG' dropdown is not viewable

### ISSUE THREAD

**Issue by yashk0thari** [fossasia/gci17.fossasia.org#616]
### Expected results
'ENG' dropdown to be viewable

### Actual results
'ENG' dropdown not viewable

### Steps to reproduce the issue
go to gci17.fossasia.org

## Would you like to work on this
YES !!

**Comment by yashk0thari** [comment]
![screen shot 2017-12-29 at 11 34 03 pm](https://user-images.githubusercontent.com/33036913/34444000-e9dae1e2-ecf0-11e7-84e8-e75b3608c262.png)

**Comment by yashk0thari** [comment]
![screen shot 2017-12-30 at 10 21 01 am](https://user-images.githubusercontent.com/33036913/34451427-50254e38-ed4b-11e7-9494-3740e2033e03.png)

**Comment by yashk0thari** [comment]
i am having this problem; have checked in multiple browsers (Chrome; Safari) ...

**Comment by supunTE** [comment]
Please close this issue now, Now there is not any problem!

**Comment by supunTE** [comment]
Please close this issue now, Now there is not any problem! Now we using G Translate plugin
