### ISSUE TITLE
Icons  are not appearing at many places

### ISSUE THREAD

**Issue by ParthS007** [fossasia/gci17.fossasia.org#624]
### Expected results
Icons and logo should be there.

### Actual results (Providing Screenshots)
**Below Header**
![image](https://user-images.githubusercontent.com/24358501/34449455-5f0dbd2c-ed1e-11e7-8f0e-05b2de7f28e1.png)

![image](https://user-images.githubusercontent.com/24358501/34449483-a48e549c-ed1e-11e7-9f7d-c2b82e02b954.png)

**Comment by harshit98** [comment]
@ParthS007 Please check if all bugs have been solved and close the issue.
