### ISSUE TITLE
Students section is not appearing 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/gci17.fossasia.org#626]
### Expected results
Students should be visible

### Actual results
![image](https://user-images.githubusercontent.com/24358501/34449578-9a169834-ed1f-11e7-9b54-408a650fb5c6.png)

**Comment by 0x48piraj** [comment]
![image](https://user-images.githubusercontent.com/5800726/34449712-6aa4eefa-ed21-11e7-8920-a8c5680bd07e.png)

This too @ParthS007
