### ISSUE TITLE
Wrong image in Blog Section

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/gci17.fossasia.org#629]
### Expected results
Correct image.
### Actual results
![image](https://user-images.githubusercontent.com/5800726/34450079-05a04332-ed27-11e7-9efe-8e9ed05c3daf.png)

## Would you like to work on this
No !! Ping @AmanSingh200

**Comment by harshit98** [comment]
@0x48piraj Can you fix it by keeping another image related to programming stuff or related?

**Comment by 0x48piraj** [comment]
Yeah, why not! 
Will do. :+1:
