### ISSUE TITLE
Indentation of files

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/gci17.fossasia.org#638]
### Expected results
All files should be indented propely

### Actual results
Files are not properly indented

## Would you like to work on this
Yes

**Comment by samyakbvs** [comment]
claiming

**Comment by supunTE** [comment]
@vaibhavsingh97 Please close this . I made a issue already for this https://github.com/fossasia/gci17.fossasia.org/issues/547 . And I am working on it. Please give few days. I will make it.

**Comment by vaibhavsingh97** [comment]
Duplicate of #547
