### ISSUE TITLE
Thank you for contributing

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/gci17.fossasia.org#645]
The section has disappeared

**Comment by samyakbvs** [comment]
Working on it!

**Comment by harshit98** [comment]
What's the status @samyakbvs ?

**Comment by apoorvkhare07** [comment]
@harshit98 Can you please explain the issue further ?
If @samyakbvs is not working on it, I would like to work on this.

**Comment by aryan-02** [comment]
Hi, this was fixed in PR #801

**Comment by aryan-02** [comment]
And Issue #741
