### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by kaine119** [fossasia/gci17.fossasia.org#67]
The overall layout for the GCI pages over the past few years have been quite similar: many different sections (a map, the students/mentors/contributors gallery, projects, and so on) all on one large homepage.

While a single page makes sense at smaller scales, some issues might crop up as more things are added to the page:
* greater risk that a merge conflict might break the page
* (more importantly) **it takes longer to load the page** and its large number of resources.

For instance, gci16.fossasia.org pulls in about 600 requests, or **24MB** in resources, including scripts and images.

![2017-12-02_10-19-49](https://user-images.githubusercontent.com/9492636/33510723-b5e914fa-d74a-11e7-8acb-7c061cc0a0c9.png)

That took almost **40s** to download on a home broadband connection; it would take even longer to download on a mobile connection.

Additionally, not all of the scripts / images downloaded might be noticed by a user; not everyone might look at the Contributors section, for instance.

Suggest moving each section of the page into individual pages; the front page could have a small preview of each section, which links to the respective page.

**Comment by kaine119** [comment]
So far I've moved the mentor section out into its own file; working files on [my fork](https://github.com/kaine119/gci17.fossasia.org/tree/separate-pages)

**Comment by ba11b0y** [comment]
@kaine119 Good point 👍 
@mariobehling Maybe we could switch to a Progressive Web App approach.
Thoughts?

**Comment by kubami9** [comment]
And how about language translations? They are going to be in the separate html files, right?

**Comment by kaine119** [comment]
> @mariobehling Maybe we could switch to a Progressive Web App approach.

I'd be happy to help :smile:

> And how about language translations? They are going to be in the separate html files, right?

Depends on how the translations are going to be implemented:
* if new `index.html` files are going to be made for other languages and put in a subdirectory (e.g. `gci17.fossasia.org/pl/index.html`), then copies of the section html files should be made for each language
* if translations are put directly in `index.html` and hidden as needed, the same will be done in the section html files
* if you use a localization framework (e.g. [l20n.js](http://l20n.org/)), all the strings in `index.html` and the separate html files will be replaced with templates that are then filled out with appropriate translations by the framework.
