### ISSUE TITLE
Hitesh Reddy's image is not visible in website 

### ISSUE THREAD

**Issue by yashk0thari** [fossasia/gci17.fossasia.org#670]
### Expected results
Visible image of blogger (Hitesh Reddy)

### Actual results
Not visible image of blogger (Hitesh Reddy)

### Steps to reproduce the issue
go to gci17.fossasia.org
go to blog section
scroll down 

## Would you like to work on this
YES !!

**Comment by nzec** [comment]
Close this.

**Comment by yashk0thari** [comment]
Ohk :D Happy New Year

**Comment by nzec** [comment]
@Beta-King Happy New Year 🎉
