### ISSUE TITLE
Want To Change My Photo In Fossasia Website Of Google Code In 2017-2018

### ISSUE THREAD

**Issue by ghost** [fossasia/gci17.fossasia.org#672]
I want my current profile picture to be uploaded instead of my previous photo please help me someone

**Comment by 0x48piraj** [comment]
Yeah! Sure
What kind of help do you need ?

**Comment by ghost** [comment]
i wanted you to change my old image from fossasia website and upload my
current profile picture to it...

**Comment by 0x48piraj** [comment]
Okay, but I suggest you to DIY.

@ParthS007 @vaibhavsingh97 What do you all say ?

**Comment by ghost** [comment]
DIY MEANS

**Comment by 0x48piraj** [comment]
Do it yourself.

Anyways, send the picture of 240x240 size. If mentors will agree I or any other student will do that.

**Comment by ghost** [comment]
ok please .. please do it for me..

**Comment by 0x48piraj** [comment]
@harshit98 Please help.

**Comment by nzec** [comment]
@demonsingh336 All right. I am on it! Can you tell me the pages in which your photo needs to be replace? (I am guessing only the GCI website)

And should I change it into your current Github image?

**Comment by ghost** [comment]
yess.... change it by my current github profile picture...
website is gci17.fossasia.org
