### ISSUE TITLE
Resolve all the console errors.

### ISSUE THREAD

**Issue by harshit98** [fossasia/gci17.fossasia.org#678]
### Expected results

No console errors should be present when gci17.fossasia.org is visited.

### Actual results

A lot of console errors are coming up when gci17.fossasia.org is visited.

Here are some screenshots:

![screen shot 2017-12-31 at 5 08 16 pm](https://user-images.githubusercontent.com/22245418/34461363-830fe850-ee4d-11e7-8569-4063ad891a8f.png)
![screen shot 2017-12-31 at 5 08 40 pm](https://user-images.githubusercontent.com/22245418/34461365-849fb4ca-ee4d-11e7-9032-4f7aab4e00b6.png)

**Comment by realslimshanky** [comment]
I would like to work on this issue. Please assign me as I'll send the PR as soon as I'm finished.

**Comment by abishekvashok** [comment]
Please go on @realslimshanky

**Comment by realslimshanky** [comment]
Thanks, @abishekvashok. I'll be replying with a PR soon.

**Comment by realslimshanky** [comment]
I'm unable to build the app for Heroku. The web server is not running after deployment. Please guide me to what I'm doing wrong.
cc: @harshit98 @abishekvashok 

Update. I've uploaded the site to github.io instead in order to debug it.
