### ISSUE TITLE
Getting a XSS warning from NoScript Extension

### ISSUE THREAD

**Issue by realslimshanky** [fossasia/gci17.fossasia.org#688]
### Expected results
There should be no warning regarding any of the js scripts used on the website.

### Actual results
The warning is displayed below. 
![image](https://user-images.githubusercontent.com/10004530/34462782-2a38b1fc-ee71-11e7-93c6-080c0829e4bc.png)

### Steps to reproduce the issue
Install [NoScript](https://noscript.net/) extension on your browser and visit gci.fossasia.org

## Would you like to work on this
Sorry, I'm currently occupied, if someone could look into this issue please do. I'll be happy to fix it up after I'm free from other issues.

**Comment by m1guelpf** [comment]
https://github.com/fossasia/gci17.fossasia.org/pull/754
