### ISSUE TITLE
Cannot install Jekyll with just ruby on linux

### ISSUE THREAD

**Issue by realslimshanky** [fossasia/gci17.fossasia.org#689]
### Expected results
Jekyll can be installed after installing required dependencies and following steps 1 and 2 given in [installation file](https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/installation/installation_linux.md)

### Actual results
Jekyll cannot be installed and throws following error.
`ERROR: Failed to build gem native extension.`

### Steps to reproduce the issue
Simply try to follow the steps provided in the [installation file](https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/installation/installation_linux.md) on a clean OS (i.e. with no previous instances of ruby or ruby-dev installed)

## Would you like to work on this
I would like to work on this issue since it's an easy fix.

**Comment by abishekvashok** [comment]
Link is returning 404

**Comment by realslimshanky** [comment]
@abishekvashok, fixed.
