### ISSUE TITLE
Change animations in "Whats happen in the last summit" box.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#698]
### Expected results
Remove and add new animation for this picture that not improve site quality and speed.

### Actual results
![animation](https://user-images.githubusercontent.com/33794760/34465636-04b9bef6-eedc-11e7-91af-19aa32e218ef.png)
This animation makes it slower and decrease site quality. 

### Steps to reproduce the issue
Change codes in js and css files!

## Would you like to work on this
If you like to work, no problem work!

**Comment by nzec** [comment]
@STEdirisuriya Already solved in #569
