### ISSUE TITLE
Blogs, Videos sections are not responsive.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#699]
### Expected results
Make them responsive.

### Actual results
Those sections are not responsive.

### Steps to reproduce the issue
Make those as other sections.

## Would you like to work on this
Anyone work!

**Comment by nzec** [comment]
@STEdirisuriya I think this was fixed by #569 . If you think that this is not completely responsive, please attach an image.

**Comment by STEdirisuriya** [comment]
Oh! yes it works. But on local not working

**Comment by nzec** [comment]
@STEdirisuriya Rebase your repository. It is `52 commits behind fossasia:gh-pages. `

**Comment by supunTE** [comment]
@duttaditya18 Sorry for that I didn't see
