### ISSUE TITLE
Problems in activities.html

### ISSUE THREAD

**Issue by nzec** [fossasia/gci17.fossasia.org#706]
### Expected results
There are quite a few problems in the activities.html page.

* [x] Add activities to nav bar.
* [x] It says issues in the button, change that to activities.
* [x] <s>The button takes the user to the issues page, instead, it should take the user to here `https://github.com/fossasia/gci17.fossasia.org/issues?utf8=%E2%9C%93&q=is%3Aopen+` </s> 
([Not required](https://github.com/fossasia/gci17.fossasia.org/pull/707#pullrequestreview-86057480))
* [ ] It currently shows only 30 activities, add pagination and show all the activities in different pages. [Learn more](https://developer.github.com/v3/guides/traversing-with-pagination/)
* [ ] Add a more accessible UI for scrolling down. [Original Conversation.](https://github.com/fossasia/gci17.fossasia.org/pull/607#pullrequestreview-85982056)

### Would you like to work on this
Help needed! I will try to work on as many as I can.

**Comment by nzec** [comment]
#707 Solves the first 3 issues.

**Comment by duttaditya18** [comment]
@harshit98 Can you add the help needed label?

**Comment by nzec** [comment]
@harshit98 @ParthS007 Can you add the help needed label?
