### ISSUE TITLE
Add example to YML files.

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#708]
### Expected results
Add example for how to add details on YML files.
like this:
```
# Please add your entries to a random position in the file.
# This is to remove conflicts with other people adding entries.
# the format is:
#- name: Mario Behling
#  github: Link to github repository of project (username/projectName)
#  author: name of author of project
#  image: projectname.png (upload the image with that name to /img/projects/)
```

### Actual results
There are only one example in `Students_Projects.yml ` like above. 

### Steps to reproduce the issue
Add comments like above into all YML files.

## Would you like to work on this
Anyone work on this.

**Comment by nzec** [comment]
@STEdirisuriya Claiming! ❤️
