### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/gci17.fossasia.org#715]
![screen shot 2018-01-01 at 3 54 08 pm](https://user-images.githubusercontent.com/34275800/34467477-483a68fa-ef19-11e7-825d-37f389027f3c.png)

Align them properly 
working on it

**Comment by aryan-02** [comment]
Hi
I have a fix for this: it can be solved using a flexbox with media queries.

**Comment by aryan-02** [comment]
Okay, fixed.

**Comment by isuruAb** [comment]
hello @aryan-02  , @samyakbvs  is already working on it.
