### ISSUE TITLE
Make the video section responsive

### ISSUE THREAD

**Issue by nzec** [fossasia/gci17.fossasia.org#742]
### Expected results
A responsive video section.

### Actual results
Not responsive.

The blog section was made responsive by #569 but the same styles were not applied on the Video Section.

## Would you like to work on this
**If anyone wants to work on this, go ahead!**

**Comment by ParthS007** [comment]
Please update @duttaditya18

**Comment by duttaditya18** [comment]
@ParthS007 Anyone can work on this. Do you want me to work on this again? If yes, can you tell me what was wrong with my old PR.
