### ISSUE TITLE
Website: Improve Loading Times and Code Quality of FOSSASIA Google Code-In website

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/gci17.fossasia.org#755]
### Expected results
Make our website fast! (if not blazing fast!)

### Actual results
Our website lags now, and it's loading time is greater than other websites.

### Steps to reproduce the issue
**_Visit : https://gci17.fossasia.org/_**

## Would you like to work on this

**GCI Students!**

**Comment by 0x48piraj** [comment]
@ParthS007 @vaibhavsingh97 @harshit98 Please add `help_wanted` label.

**Comment by harshit98** [comment]
Reopening it. Still more work has to be done.

**Comment by 0x48piraj** [comment]
Thanks @anshumanv :wink:

**Comment by ParthS007** [comment]
@0x48piraj  Please update or close this if resolved 👍

**Comment by 0x48piraj** [comment]
I don't think now anyone will do task, so closing it :+1: 
I'll improve the website myself, and specify in Pull Request.
