### ISSUE TITLE
Problems with repositories.html

### ISSUE THREAD

**Issue by nzec** [fossasia/gci17.fossasia.org#774]
There are the following problems which must be fixed : 
* [ ] Change layout in order to not have an image. (Like in activities.html)
* [ ] Make the page more accessible. Like, have a button in index.html to go to this page.

### Would you like to work on this
I am working on the first point.

**Comment by Ploypiti** [comment]
@duttaditya18 Can I work on point 2?

**Comment by anshumanv** [comment]
Sure @Ploypiti
