### ISSUE TITLE
Add search box for contributors, students, mentors, videos, blogs sections 

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#776]
### Expected results
Add search box for contributors, students, mentors, videos, blogs sections  for find them easily

### Actual results
No search box yet.

## Would you like to work on this
If you like to work, no problem!

**Comment by nzec** [comment]
@STEdirisuriya Working on Mentors and Students!

**Comment by jamessandy** [comment]
can I help ?

**Comment by nzec** [comment]
@jamessandy Sure! Go on!

**Comment by verma1997** [comment]
Hi. I want to help. Is this issue is only about creating a search box? I mean what you really want in that search box.

**Comment by nzec** [comment]
@verma1997 We want to create a search box that searches and displays the result. Sure, go ahead!
