### ISSUE TITLE
Map is completely broken!

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/gci17.fossasia.org#786]
### Expected results
Map should be responsive and should work!
### Actual results
![image](https://user-images.githubusercontent.com/5800726/34554747-66053026-f154-11e7-8ac5-cca398cf9854.png)

## Would you like to work on this
Yes, but anyone can take it without asking! just put a comment and start working :+1:

**Comment by realslimshanky** [comment]
![image](https://user-images.githubusercontent.com/10004530/34734845-45632e48-f593-11e7-88bb-1f900d3fa3bb.png)
Map works for me, could you please check if your browser is allowing scripts to import OpenLayers/open street maps resources? I think the problem lies on the client side.

**Comment by 0x48piraj** [comment]
Yes, It's not working.

**Comment by ParthS007** [comment]
@0x48piraj Please update or close this if resolved 👍

**Comment by 0x48piraj** [comment]
It still not works for my laptop.
I'm closing this, if the bug arises, someone will open it.
