### ISSUE TITLE
asciicast dimensions are broken

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/gci17.fossasia.org#795]
### Expected results
Same sized icons.
### Actual results
Different sized icons.
![image](https://user-images.githubusercontent.com/5800726/34577155-3883e7d0-f1a6-11e7-89d5-b12e549551a5.png)

### Steps to reproduce the issue
Visit our website
## Would you like to work on this

I will suggest @abishekvashok to-do it. *(hint : he made img-checker last year.)*

**Comment by supunTE** [comment]
@0x48piraj Thank you finding issues with ascciicast section, But there is a problem, 
The asciicast section uses images from direct by asciinema site, So you have to give a method any other  good sole without adding images into site folder, If we use  site folder it's not good idea. Please try to give an another idea with upload it direct from asciicast site.

**Comment by ParthS007** [comment]
@0x48piraj Please update or close this if resolved 👍

**Comment by 0x48piraj** [comment]
@ParthS007 
It's still present.
