### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by kubami9** [fossasia/gci17.fossasia.org#83]
Is it good time to add translations to the website? I'd really like to add Polish translation and I'm ready to regularly update it and commit :)

**Comment by dumprop** [comment]
I can help with Russian language

**Comment by supunTE** [comment]
I'll trying to add a new translation. Can I know the Do you want new translate page separately or not?

**Comment by dumprop** [comment]
As you wish and what is possible to me :)

**Comment by supunTE** [comment]
I am working on this

**Comment by dumprop** [comment]
On Russian language?

**Comment by supunTE** [comment]
no, My language. I think I can add new language for this. Didn't?

**Comment by supunTE** [comment]
We have to use jekyll it is better better way for this
Read this this will be better way - https://www.sylvaindurand.org/making-jekyll-multilingual/

**Comment by 0x48piraj** [comment]
@kubami9 @h0n3yc4k3 
Read the https://gitter.im/fossasia/fossasia channel. I @Ploypiti & @STEdirisuriya were discussing about this.  :+1:

**Comment by YashKumarVerma** [comment]
so have we got any solid idea or plan ?

**Comment by kubami9** [comment]
After reading the discussion, I think that Jekyll method proposed by @STEdirisuriya might be the best one. After all we have to create separate files either way. Unless we decide to use GT or something similar but honestly, I think it won't be good quality translation and good decision, especially if there are students from all around the globe who could take a part in translating process.
I also don't think that translating only for few - only Asian - languages is a good idea, it doesn't mean we've gonna have less to do but only that few of us gonna take a part in it.
Of course that's just my opinion and I'd like to know your ideas or vision 😄

**Comment by Ploypiti** [comment]
We can just list down the pros & cons and make a reasonable decision if you'd like.

**Comment by supunTE** [comment]
We can done this part by part

**Comment by supunTE** [comment]
See this issue
https://github.com/fossasia/gci17.fossasia.org/issues/445

**Comment by harshit98** [comment]
Closing this issue. Follow up translations issue here: #445
