### ISSUE TITLE
[GCI Task]: Add/Improve CI and tests integration with Travis and other tools.

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#84]
Travis ci build for this project is still disabled. Please enable it in the Travis ci dashboard. https://travis-ci.org

**Comment by ba11b0y** [comment]
@mariobehling Do we really need a travis build for this project?

**Comment by harshit98** [comment]
**OBJECTIVE:**

Add and improve Travis CI in GCI 2017 FOSSASIA repository.

**REQUIREMENT:**

Knowledge of Travis CI.

**OUTCOME:**

A pull request with improvements in Travis CI or addition of Travis CI.

**LINK:**

- Refer to Travis CI official documentation: https://docs.travis-ci.com/user/getting-started/
- Time period: 3 days.
- Type: Training.
- Advanced Task.

**Comment by abishekvashok** [comment]
I would like to work on it @harshit98 Can I?

**Comment by abishekvashok** [comment]
@harshit98 can we integrate https://github.com/abishekvashok/img_checker for checking if the images are in proper dimensions?

**Comment by abishekvashok** [comment]
Also pls activate the repository on Travis

![screenshot from 2017-12-06 17-26-58](https://user-images.githubusercontent.com/8947010/33660685-b9c02f74-daaa-11e7-9a25-c031a33ca169.png)

Go to this link to activate: https://travis-ci.org/fossasia/gci17.fossasia.org/

**Comment by abishekvashok** [comment]
Ping @fossasia/fossasia-gci

**Comment by chashmeetsingh** [comment]
Travis has been enabled, you can proceed.

**Comment by abishekvashok** [comment]
@chashmeetsingh @harshit98 which is the task I should claim?

**Comment by abishekvashok** [comment]
Claimed task for advanced issue

**Comment by harshit98** [comment]
@hpdang I'm opening this issue again. This issue is a GCI task. : )

**Comment by m1guelpf** [comment]
Also related to #221

**Comment by abishekvashok** [comment]
Researching what else could be done.

**Comment by abishekvashok** [comment]
Current Paralell architecture could be improved much more. The script is safe enough now to be merged into .travis.yml

**Comment by harshit98** [comment]
This issue has been completed successfully. Closing it.
