### ISSUE TITLE
Enhance slider and header

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci17.fossasia.org#86]
The header and slider have really minute improvements,

Therefore we have to:
- [x] Update Header links
- [ ] Enhance the slider with fossasia specific text and images.

**Comment by abishekvashok** [comment]
Working on it

**Comment by nzec** [comment]
What exactly is meant by sliders? I am working on the header links.

**Comment by YashKumarVerma** [comment]
I'm working on slider text. Any specifics regarding the content sir?

**Comment by YashKumarVerma** [comment]
@duttaditya18 the slider means refers to the top of the page which has that cover background and some lines.
The thing that holds *meet fossasia, the... * and the other slide being *meet foundary... *

**Comment by nzec** [comment]
@YashKumarVerma Oh okay. Thanks. I will work on the Header Links!

**Comment by kubami9** [comment]
Can I work on the header images?

**Comment by nzec** [comment]
@abhishekvashok Take a look at #101

**Comment by nzec** [comment]
@abishekvashok The first checklist was solved by #101. Please mark "Update Header links" as done.

My task was : https://codein.withgoogle.com/dashboard/task-instances/5173243537260544/

**Comment by YashKumarVerma** [comment]
I think the issue is solved now.
