### ISSUE TITLE
The blog post links should be displaying titles as default

### ISSUE THREAD

**Issue by shashwat1002** [fossasia/gci17.fossasia.org#876]
### Expected results
The blog post links should be displaying titles as default
### Actual results
The pictures of authors are displayed as default, this leads to several images of the same person for different blog post and the user isn't able to see the tit;e of the blog post unless he/she hovers
### Steps to reproduce the issue
scroll over to the blogs section
## Would you like to work on this
Yes!

**Comment by ParthS007** [comment]
@shashwat1002 Please update or close this if resolved 👍
