### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by choyiny** [fossasia/gci17.fossasia.org#9]
Currently going to http://whatcanidofor.fossasia.org redirects to http://whatcanidofor.fossasia.org/whatcanidofor.fossasia.org/en/index.html.

**Comment by hvardhanx** [comment]
Probably this line redirects : https://github.com/fossasia/whatcanidofor.fossasia.org/blob/gh-pages/index.html#L6

**Comment by hvardhanx** [comment]
Fixed https://github.com/fossasia/whatcanidofor.fossasia.org/commit/798195d2e72f287eb84165277e9234faa596dae0
