### ISSUE TITLE
Multiple design flaws

### ISSUE THREAD

**Issue by aryan-02** [fossasia/gci17.fossasia.org#905]
### Expected results
A complete redesign or just improvements to the design of the website, keeping in mind the principles of minimalism, clean design, consistency and blank spaces while preserving the actual content. This ideally should be achieved through partial fixes of this issue. 

Here are some resources for reference.
https://material.io/guidelines/
https://thenextweb.com/dd/2017/11/08/psychology-web-design/
https://envato.com/blog/scroll-hijacking/

### Actual results
Here are some (but not all) noticeable issues with the current design:
#### Consistency
The hover animations in the contents of the galleries aren't consistent.
In the mentors' gallery, the effect is a translucent overlay that has social links, whereas, in the Contributors' gallery, the overlay appears but the container moves down. Similarly, the Student Projects and Blogs gallery have totally different hover effects.
#### Smooth scroll
It'll be better to not have a smooth scroll, since it blocks users from normally scrolling down quickly.
More information can be found here: https://envato.com/blog/scroll-hijacking/
#### Navigation
On the navigation bar, only external links should be put. Too many links can be overwhelming to a casual visitor.
### Steps to reproduce the issue
Just open the site in a browser such as Google Chrome and you'll find the issues. If this is not the first time you're visiting the site, press F12, then right-click the Reload button and select the "Empty Cache and Hard Reload" option.
## Would you like to work on this
Yes, however, as mentioned before, we'll need multiple partial fixes. It'll be great if multiple people work on this.
For those interested in working on this, it's highly recommended that you have a look at each link mentioned above.

**Comment by samyakbvs** [comment]
Firstly I am improving the navbar

**Comment by aryan-02** [comment]
Great! Please go ahead.
Till then, I'm removing the smooth scroll

**Comment by samyakbvs** [comment]
Fixing the blog section

**Comment by ParthS007** [comment]
@aryan-02  Please update or close this if resolved 👍
