### ISSUE TITLE
Header often not loading as expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#958]
The header area sometimes does not load the javascript effects. Probable cause is that the Javascript effects are stored in the footer instead of the header.

Please help to fix this.

![screenshot from 2018-02-01 21-37-39](https://user-images.githubusercontent.com/1583873/35702065-4c546192-0798-11e8-8f8e-57ff49b624e8.png)

**Comment by ankurg22** [comment]
Please close this. It is solved in #980
