### ISSUE TITLE
Add Issue and PR template 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/gci17.fossasia.org#96]
Add an Issue and a PR template just like other repositories of FOSSASIA  and Put it in the desired .github folder.

Please go through it [https://github.com/fossasia/gci16.fossasia.org/tree/gh-pages/.github](https://github.com/fossasia/gci16.fossasia.org/tree/gh-pages/.github)

**Comment by YashKumarVerma** [comment]
Working on it

**Comment by ParthS007** [comment]
Sure go ahead :+1:
