### ISSUE TITLE
Take out moving right/left arrow icons on header

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#963]
The icons left/right arrow are duplicating the feature that is already implemented below. It is also not a high priority to have a feature to switch between images left and right.

Please take this out.

![screenshot from 2018-02-01 22-40-56](https://user-images.githubusercontent.com/1583873/35704890-2910f502-07a1-11e8-8bf4-d6a7ceb07daa.png)

**Comment by rupav** [comment]
claiming this.

**Comment by ankurg22** [comment]
@rupav Are you working on this? Or can I claim?

**Comment by rupav** [comment]
You can work on it

**Comment by ankurg22** [comment]
Thankyou

**Comment by ankurg22** [comment]
Also close this one. Solved in #980
