### ISSUE TITLE
Drop-down has red overlay on drop-down: It should not

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#971]
The red background on the drop down menu does not make sense here as we are not using the standard FOSSASIA style here.

Please revert this color change. Research the previous gray color and revert to it.

![screenshot from 2018-02-09 11-46-34](https://user-images.githubusercontent.com/1583873/36024117-fea24b9c-0d8e-11e8-8298-94011ba1a4cd.png)

**Comment by yashLadha** [comment]
Shall I send a PR for this, or is meant for GCI students only

**Comment by ankurg22** [comment]
@yashLadha Shall I proceed or are you working on this? If yes, then here is the pull request which changed the scroll over color. https://github.com/fossasia/gci17.fossasia.org/pull/229/
