### ISSUE TITLE
Info icon on participants become -black- invisible on scroll over

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#974]
The info icon on mentors, participants etc. becomes black on scroll over and it is hard to see. It should be light gray.

![screenshot from 2018-02-09 11-54-58](https://user-images.githubusercontent.com/1583873/36024548-58bdacc4-0d90-11e8-9d88-143b48cd8ed2.png)

**Comment by yashLadha** [comment]
I am sending a fix for that.
