### ISSUE TITLE
Change "Contributors" section from 3 columns to 6 columns and reduce image size

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#978]
The contributors section takes up a lot of space. Please change the section from 3 columns to 6 columns and reduce image size accordingly.

![screenshot from 2018-02-09 13-35-48](https://user-images.githubusercontent.com/1583873/36028170-4e4d20d6-0d9e-11e8-88d8-a6369316ac81.png)

**Comment by prshntsingh** [comment]
claiming
