### ISSUE TITLE
Add missing mentors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci17.fossasia.org#982]
Here is a list of all mentors of 2017/18

* [ ] Alex Henrie | Alex | Henrie
* [x] Nguyen Hoang Phu | Hoang Phu | Nguyen
* [ ] Ali Ayub Khan | Ali Ayub | Khan
* [ ] Mishari Muqbil | Mishari | Muqbil
* [ ] Aric Stewart | Aric | Stewart
* [ ] Padmal | Madhushanka | Padmal
* [ ] Soong Chee Gi | Soong Chee | Gi
* [x] RAHUL TIWARI | RAHUL | TIWARI
* [x] Suneet Srivastava | Suneet | Srivastava
* [x] Rupav Jain | Rupav | Jain
* [x] Akshat Garg | Akshat | Garg
* [x] Sanskar Jethi | Sanskar | Jethi
* [ ] Gnovi | Praveen | Patil
* [x] SaptakS | Saptak | Sengupta
* [ ] Lorenz Gerber | Lorenz | Gerber
* [ ] Kristi Progri | Kristi | Progri
* [ ] Pepe Becker | Pepe | Becker
* [ ] Juan Pardo | Juan Nicolas | Pardo Martin
* [ ] Jona Azizaj | Jona | Azizaj
* [ ] Darwin Gosal | Darwin | Gosal
* [ ] astroiseur | Handoko | Suwono
* [ ] Samiullah Danish | Samiullah | Danish
* [ ] Noah Chen | Noah | Chem
* [ ] Eden | Eden | J
* [ ] VSN Reddy Janga | VSN Reddy | Janga
* [ ] Manav Jain | Manav | Jain
* [x] Nikit Bhandari | Nikit | Bhandari
* [x] Piyush Agrawal | Piyush | Agrawal
* [x] Louis | Louis | Gagnon
* [ ] Pranjal Paliwal | Pranjal | Paliwal
* [ ] Rosanne DiMesio | Rosanne | DiMesio
* [x] Tarun Kumar | Tarun | Kumar
* [ ] Subhankar Shah | Subhankar | Shaha
* [x] DEEPJYOTI MONDAL | DEEPJYOTI | MONDAL
* [ ] Akarshan Gandotra | Akarshan | Gandotra
* [ ] Harshita Gupta | Harshita | Gupta
* [x] Manish Devgan | Manish | Devgan
* [ ] Harshit Kedia | Harshit | Kedia
* [x] Parth Shandilya | Parth | Shandilya
* [x] Thiyagaraj T | Thiyagaraj | T
* [x] Vibhor Verma | Vibhor | Verma
* [x] Abhinav Khare | Abhinav | Khare
* [x] Pratyush Singh | Pratyush | Singh
* [ ] Harsh Lathwal | Harsh | Lathwal
* [ ] Mohit Manuja | Mohit | Manuja
* [ ] Mayank Tripathi | Mayank | Tripathi
* [ ] Jason Wong | Jason | Wong
* [ ] Achint Sharma | Achint | Sharma
* [ ] Anant Prasad | Anant | Prasad
* [ ] Rishi Raj | Rishi | Raj
* [ ] Kavitha E Nair | Kavitha | E Nair
* [ ] André Hentschel | André | Hentschel
* [x] Zameer Haque | Zameer Ul | Haque
* [ ] Manveer Singh | Manveer | Singh
* [ ] Dishant Khanna | Dishant | Khanna
* [ ] Yiping Deng | Yiping | Deng
* [x] Vaibhav Singh | Vaibhav | Singh
* [x] Nikhil Rayaprolu | Nikhil | Rayaprolu
* [x] Avi Aryan | Avi | Aryan
* [x] Ayush | Ayush | Gupta
* [x] Mohit Sharma | Mohit | Sharma
* [x] Yash Ladha | Yash | Ladha
* [x] Anshuman Verma | Anshuman | Verma
* [ ] Dravit Lochan | Dravit | Lochan
* [ ] Amit Tiwary | Amit | Tiwary
* [ ] Ujjwal Bhardwaj | Ujjwal | Bhardwaj
* [ ] sadboy | Varun | Kumar
* [ ] Chirag Wadhera | Chirag | Wadhera
* [ ] Chetan Kaushik | Chetan | Kaushik
* [ ] Shailesh Baldaniya | Shailesh | Baldaniya
* [ ] Chashmeet Singh | Chashmeet | Singh
* [ ] SAURABH JAIN | SAURABH | JAIN
* [x] Harshit Prasad | Harshit | Prasad
* [ ] Dilpreet Singh | Dilpreet | Singh
* [ ] Aayush Arora | Aayush | Arora
* [ ] Hon Nguyen | Hon | Nguyen
* [x] Damini Satya | Damini Satya | Kammakomati
* [x] Sudheesh Singanamalla | Sudheesh | Singanamalla
* [x] Jigyasa Grover | Jigyasa | Grover
* [x] Nicco Kunzmann | Nicco | Kunzmann
* [ ] André Rebentisch | André | Rebentisch
* [ ] Bruno Magalhães | Bruno | Magalhães
* [x] Madhav Rathi | Madhav | Rathi
* [x] Isuru Abeywardana | Isuru | Abeywardana
* [x] Shubham Padia | Shubham | Padia
* [ ] the-dagger | Harshit | Dwivedi
* [x] Sumedh Nimkarde | Sumedh | Nimkarde
* [x] hpdang | Hong Phuc | Dang
* [x] Mario Behling | Mario | Behling

**Comment by NaviRocker** [comment]
@mariobehling Sir, How can I update your Comment?
Already 42 Mentors are there on the Site https://gci17.fossasia.org/mentors

**Comment by nzec** [comment]
@naveentherocker Make a new comment and tick the required checkboxes.

**Comment by Rupeshiya** [comment]
@mariobehling  what we have to do  or we need to add those tick marks mentors or all those mentors ?

**Comment by anshumanv** [comment]
@Rupeshiya the ticked ones are already present, please help in adding the ones which are not present.
