### ISSUE TITLE
Simple fix need

### ISSUE THREAD

**Issue by supunTE** [fossasia/gci17.fossasia.org#984]
### Expected results.
Create it to seperate like first.

### Actual results
Two pictures with text overlapped
![image](https://user-images.githubusercontent.com/33794760/36063071-3573f278-0e9e-11e8-8541-13ef2b316fb6.png)

## Would you like to work on this
No

**Comment by yashLadha** [comment]
This was solved in  #972. Try to again open the website in a new tab, may be this is because of internet connectivity. @STEdirisuriya . I have tested it on two other laptops and it is working fine. Please try to check your internet connection.
